### ISSUE TITLE
Domestic Trade

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#82] opened 2016-05-21 00:32 UTC
Text on the trade button does not change for when the trade is acceptable. (For me, it still says 'you can't trade this turn' or 'set the trade you want to make')

**Comment by benjaminhafen** [comment] 2016-05-21 00:42
Duplicate of #23. Marking as duplicate and fixed.

**Closed as completed** 2016-05-24 18:43 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 1
