### ISSUE TITLE
Players same color

### ISSUE THREAD

**Issue by cwpitts** [rysav/cs340spring2016#73] opened 2016-05-20 22:51 UTC
Multiple clients can select the same color if both players join before selecting.

**Comment by cwpitts** [comment] 2016-05-20 22:53
Extension: if one player reloads (i.e. restarts the client), and selects a different color, they will have the correct view, but the view for the other players remains unchanged.

**Comment by benjaminhafen** [comment] 2016-05-20 23:04
Duplicate of #52. Marking as fixed and duplicate.

**Closed as completed** 2016-05-24 18:43 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 1
