### ISSUE TITLE
Cannot Win Or Lose

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#50] opened 2016-05-20 22:05 UTC
When a player receives 10 points for a victory, the game essentially freezes and does not allow action (although occasionally you can roll) No win or lose dialog is given.
Thrown exception:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.points.PointsController.update(PointsController.java:64)
        at java.util.Observable.notifyObservers(Unknown Source)
        at java.util.Observable.notifyObservers(Unknown Source)
        at client.ClientManager.notifyObservers(ClientManager.java:108)
        at client.ClientManager.setModel(ClientManager.java:63)
        at client.communication.ServerPoller$1$1.run(ServerPoller.java:73)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by benjaminhafen** [comment] 2016-05-20 22:59
Duplicate of #47. Marking as duplicate and fixed.

**Closed as completed** 2016-05-24 18:43 UTC
Labels: Duplicate, Fixed, P2: Blocking gameplay, Phase 2, Team 1
