### ISSUE TITLE
Temporary join button

### ISSUE THREAD

**Issue by cwpitts** [rysav/cs340spring2016#61] opened 2016-05-20 22:32 UTC
Reproduce: Start client, sign in/register new user, button appears

**Comment by benjaminhafen** [comment] 2016-05-20 22:46
Duplicate of #37. Marking as Duplicate and Fixed. This is the third time this issue has been posted. If you could please check existing issues before posting, we would appreciate it!

**Closed as completed** 2016-05-24 18:43 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 1
